[tool.poetry]
name = "ratting_project"
version = "0.1.0"
description = "A project to manage product ratings"
authors = ["Milon Das"]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"